import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>EAM | Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css?family=Raleway&display=optional"></link>
			</Head>

			<main>
				<h1>This is a Title</h1>
				<h2>This is a heading</h2>
				<h3>This is a subheading</h3>
				<p>this is paragraph text running on and on.</p>
			</main>

			<footer></footer>
		</div>
	);
}
